# Generated by Django 3.2.15 on 2022-12-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_number', models.CharField(max_length=48, verbose_name='Asset number')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('serial_number', models.CharField(blank=True, max_length=48, null=True, verbose_name='Serial number')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['property_number'],
            },
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Item group',
                'verbose_name_plural': 'Item groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Item state',
                'verbose_name_plural': 'Item state',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('exclusive', models.BooleanField(default=False, verbose_name='Exclusive')),
            ],
            options={
                'verbose_name': 'Asset state',
                'verbose_name_plural': 'Asset states',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=32, verbose_name='Last name')),
                ('second_last_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Second last name')),
                ('first_name', models.CharField(max_length=32, verbose_name='First name')),
                ('second_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Second name or initial')),
                ('inventory', models.ManyToManyField(blank=True, to='assets.Item', verbose_name='Assigned assets')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['last_name', 'second_last_name', 'first_name', 'second_name'],
            },
        ),
    ]
