# Generated by Django 3.2.15 on 2022-12-09 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='itemstate',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.item', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='itemstate',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.state', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='items',
            field=models.ManyToManyField(blank=True, to='assets.Item', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.itemtemplate', verbose_name='Item template'),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.location', verbose_name='Location'),
        ),
    ]
