# Generated by Django 3.2.15 on 2022-12-09 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='User defined ID')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Issue date')),
                ('required_date', models.DateField(blank=True, null=True, verbose_name='Date required')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Purchase order',
                'verbose_name_plural': 'Purchase orders',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Purchase order item status',
                'verbose_name_plural': 'Purchase order item status',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Purchase order status',
                'verbose_name_plural': 'Purchase order status',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='User defined ID')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Issue date')),
                ('required_date', models.DateField(blank=True, null=True, verbose_name='Date required')),
                ('budget', models.PositiveIntegerField(blank=True, null=True, verbose_name='Budget')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('originator', models.CharField(blank=True, max_length=64, null=True, verbose_name='Originator')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Purchase request',
                'verbose_name_plural': 'Purchase requests',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Purchase request status',
                'verbose_name_plural': 'Purchase request status',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(verbose_name='Quantity')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('item_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.itemtemplate', verbose_name='Item template')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='movements.purchaserequest', verbose_name='Purchase request')),
            ],
            options={
                'verbose_name': 'Purchase request item',
                'verbose_name_plural': 'Purchase request items',
            },
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movements.purchaserequeststatus', verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Agreed price')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('qty', models.PositiveIntegerField(verbose_name='Quantity')),
                ('received_qty', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='received')),
                ('item_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.itemtemplate', verbose_name='Item template')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='movements.purchaseorder', verbose_name='Purchase order')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movements.purchaseorderitemstatus', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Purchase order item',
                'verbose_name_plural': 'Purchase order items',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movements.purchaserequest', verbose_name='Purchase request'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movements.purchaseorderstatus', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='inventory.supplier', verbose_name='Supplier'),
        ),
    ]
