# Generated by Django 3.2.15 on 2022-12-09 08:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.CreateModel(
            name='InventoryCheckPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2022, 12, 9, 8, 4, 7, 509281, tzinfo=utc), verbose_name='Date & time')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', verbose_name='Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('address_line1', models.CharField(blank=True, max_length=64, null=True, verbose_name='Address')),
                ('address_line2', models.CharField(blank=True, max_length=64, null=True, verbose_name='Address')),
                ('address_line3', models.CharField(blank=True, max_length=64, null=True, verbose_name='Address')),
                ('address_line4', models.CharField(blank=True, max_length=64, null=True, verbose_name='Address')),
                ('phone_number1', models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone number')),
                ('phone_number2', models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone number')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('address_line1', models.CharField(blank=True, max_length=64, null=True, verbose_name='Address')),
                ('address_line2', models.CharField(blank=True, max_length=64, null=True, verbose_name='Address')),
                ('address_line3', models.CharField(blank=True, max_length=64, null=True, verbose_name='Address')),
                ('address_line4', models.CharField(blank=True, max_length=64, null=True, verbose_name='Address')),
                ('phone_number1', models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone number')),
                ('phone_number2', models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone number')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timedate', models.DateTimeField(auto_now_add=True, verbose_name='Date & time')),
                ('action', models.CharField(max_length=32, verbose_name='Action')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64, verbose_name='Description')),
                ('brand', models.CharField(blank=True, max_length=32, null=True, verbose_name='Brand')),
                ('model', models.CharField(blank=True, max_length=32, null=True, verbose_name='Model')),
                ('part_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='Part number')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('suppliers', models.ManyToManyField(blank=True, to='inventory.Supplier', verbose_name='Suppliers')),
                ('supplies', models.ManyToManyField(blank=True, related_name='_inventory_itemtemplate_supplies_+', to='inventory.ItemTemplate', verbose_name='Supplies')),
            ],
            options={
                'verbose_name': 'Item template',
                'verbose_name_plural': 'Item templates',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('date', models.DateField(default=datetime.datetime(2022, 12, 9, 8, 4, 7, 510930, tzinfo=utc), verbose_name='Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventory', verbose_name='Inventory')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.itemtemplate', verbose_name='Supply')),
            ],
            options={
                'verbose_name': 'Inventory transaction',
                'verbose_name_plural': 'Inventory transactions',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCPQty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('check_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorycheckpoint', verbose_name='Check point')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.itemtemplate', verbose_name='Supply')),
            ],
        ),
        migrations.AddField(
            model_name='inventorycheckpoint',
            name='supplies',
            field=models.ManyToManyField(blank=True, through='inventory.InventoryCPQty', to='inventory.ItemTemplate', verbose_name='Supplies'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location', verbose_name='Location'),
        ),
    ]
